# Generated by Django 5.1.5 on 2025-01-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_userpurchase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="products/images/"
            ),
        ),
    ]
