# Generated by Django 5.1.5 on 2025-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_image_url_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                default="https://john-ecommerce-bucket.s3.amazonaws.com/default.jpg",
                max_length=500,
            ),
        ),
    ]
