# Generated by Django 5.1.5 on 2025-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_image_product_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(max_length=1024),
        ),
    ]
